---
global:
  appVersion: 1.4.0

image:
  repository: artifactory.algol60.net/csm-docker/stable/csm-rie
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Specify the desired configuration for each of the RIE instances
instances:
  # - # Required Field: Xname of the RIE emulated BMC
  #   xname: x1000c0b0
  #
  #   # Required Field: Choose one of the supported RIE mockups to select what type of BMC and hardware to emulate.
  #   # List of supported mockups can be found here: https://github.com/Cray-HPE/csm-redfish-interface-emulator/tree/master/mockups
  #   mockup: CMM
  #
  #   # Optional Field: Choose from either Mountain or River.
  #   # If field not provided all mac addresses in RIE will be randomized, which is the same behavior as River. When Mountain is selected
  #   # The MAC addresses associated with the BMC will become algorithmic based off the BMC's xname.
  #   # If this field is not specified RIE will default to the behavior of River.
  #   macSchema: Mountain
  #
  #   # Optional Field: Choose from either Mountain or River.
  #   # When RIE starts up it will check Vault at secret/hms-creds/${BMC_XNAME}, and if no value exists there then will fallback to the default
  #   # password source. On CSM systems there are two sources of default BMC credentials one for Mountain and one for River. To ensure a smooth
  #   # experience discovery hardware the RIE BMC should have the credentials that either MEDS (Mountain) or hms-discovery (River) utilizes for
  #   # default creds when first trying to talk to the BMC.
  #   # If field not provided Mountain will be defaulted to.
  #   defaultPasswordSource: Mountain
  - {Xname: x1000c0b0, mockup: CMM, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s0b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s0b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s1b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s1b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s2b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s2b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s3b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s3b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s4b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s4b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s5b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s5b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s6b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s6b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s7b0, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0s7b1, mockup: EX425, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0r1b0, mockup: Slingshot_Switch_Blade, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0r3b0, mockup: Slingshot_Switch_Blade, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0r5b0, mockup: Slingshot_Switch_Blade, macSchema: Mountain, defaultPasswordSource: Mountain}
  - {Xname: x1000c0r7b0, mockup: Slingshot_Switch_Blade, macSchema: Mountain, defaultPasswordSource: Mountain}

# Specify data to populate in SLS to facilitate discovery of the emulated hardware
sls:
  Hardware:
  - Xname: x1000
    Class: Mountain
    ExtraProperties:
      # NOTE the following network information is not used for anything network related.
      # The Networks.cn.HMN key needs to exist for MEDS to discover mountain hardware from the cabinet.
      # The networks.*.*.{CIDR, Gateway,VLan} keys are needed for the HMS CT tests to pass.
      Networks:
        cn:
          HMN:
            CIDR: "10.104.0.0/22"
            Gateway: "10.104.0.1"
            VLan: 3000
          NMN:
            CIDR: "10.100.0.0/22"
            Gateway: "10.100.0.1"
            VLan: 2000

  - {Xname: x1000c0, Class: Mountain}
  - {Xname: x1000c0b0, Class: Mountain}

  - {Xname: x1000c0s0b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1001, Aliases: [nid001001]}}
  - {Xname: x1000c0s0b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1002, Aliases: [nid001002]}}
  - {Xname: x1000c0s0b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1003, Aliases: [nid001003]}}
  - {Xname: x1000c0s0b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1004, Aliases: [nid001004]}}

  - {Xname: x1000c0s1b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1005, Aliases: [nid001005]}}
  - {Xname: x1000c0s1b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1006, Aliases: [nid001006]}}
  - {Xname: x1000c0s1b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1007, Aliases: [nid001007]}}
  - {Xname: x1000c0s1b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1008, Aliases: [nid001008]}}

  - {Xname: x1000c0s2b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1009, Aliases: [nid001009]}}
  - {Xname: x1000c0s2b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1010, Aliases: [nid001010]}}
  - {Xname: x1000c0s2b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1011, Aliases: [nid001011]}}
  - {Xname: x1000c0s2b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1012, Aliases: [nid001012]}}

  - {Xname: x1000c0s3b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1013, Aliases: [nid001013]}}
  - {Xname: x1000c0s3b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1014, Aliases: [nid001014]}}
  - {Xname: x1000c0s3b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1015, Aliases: [nid001015]}}
  - {Xname: x1000c0s3b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1016, Aliases: [nid001016]}}

  - {Xname: x1000c0s4b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1017, Aliases: [nid001017]}}
  - {Xname: x1000c0s4b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1018, Aliases: [nid001018]}}
  - {Xname: x1000c0s4b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1019, Aliases: [nid001019]}}
  - {Xname: x1000c0s4b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1020, Aliases: [nid001020]}}

  - {Xname: x1000c0s5b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1021, Aliases: [nid001021]}}
  - {Xname: x1000c0s5b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1022, Aliases: [nid001022]}}
  - {Xname: x1000c0s5b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1023, Aliases: [nid001023]}}
  - {Xname: x1000c0s5b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1024, Aliases: [nid001024]}}

  - {Xname: x1000c0s6b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1025, Aliases: [nid001025]}}
  - {Xname: x1000c0s6b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1026, Aliases: [nid001026]}}
  - {Xname: x1000c0s6b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1027, Aliases: [nid001027]}}
  - {Xname: x1000c0s6b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1028, Aliases: [nid001028]}}

  - {Xname: x1000c0s7b0n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1029, Aliases: [nid001029]}}
  - {Xname: x1000c0s7b0n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1030, Aliases: [nid001030]}}
  - {Xname: x1000c0s7b1n0, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1031, Aliases: [nid001031]}}
  - {Xname: x1000c0s7b1n1, Class: Mountain, ExtraProperties: {Role: Compute, NID: 1032, Aliases: [nid001032]}}
