---
apiVersion: batch/v1
kind: Job
metadata:
  name: csm-redfish-interface-emulator-loader-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name:  "csm-redfish-interface-emulator-loader"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  "csm-redfish-interface-emulator-loader"
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      containers:
        - name: loader
          image: "{{ $.Values.image.repository }}:{{ $.Values.global.appVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args: ["sls_loader.py", "/metadata.json"]
          volumeMounts:
            - mountPath: /metadata.json
              subPath: metadata.json
              name: metadata-cm
      volumes:
        - name: metadata-cm
          configMap:
            name: csm-redfish-interface-emulator-metadata