---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csm-redfish-interface-emulator-metadata
  labels:
    app.kubernetes.io/name:  "csm-redfish-interface-emulator"
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
data: 
  metadata.json: |-
{{ .Values.sls | toJson | indent 4 }}